name: novnc-unofficial
base: core18 # the base snap is the execution environment for this snap
version: 1.2.0
summary: Open Source VNC client using HTML5 (WebSockets, Canvas)
description: |
  Open Source VNC client using HTML5 (WebSockets, Canvas).
  noVNC is both a VNC client JavaScript library as well as an
  application built on top of that library. noVNC runs well in any
  modern browser including mobile browsers (iOS and Android).

grade: stable
confinement: strict

parts:
    novnc:
        source: https://github.com/novnc/noVNC/archive/v1.2.0.tar.gz
        plugin: dump
        stage-packages:
            - bash
            - jq
            
    websockify:
        source: https://github.com/novnc/websockify.git
        source-type: git
        plugin: python
        stage-packages:
            - python3-numpy

hooks:
    configure:
        plugs: [network, network-bind]

apps:
    novnc:
        command: utils/launch.sh
        plugs: [network, network-bind]
    novncsvc:
        command: snap/local/svc_wrapper.sh
        daemon: forking
        plugs: [network, network-bind]
