name: novnc
base: core18 # the base snap is the execution environment for this snap
version: 'latest-20190813'
summary: Open Source VNC client using HTML5 (WebSockets, Canvas)
description: |
  Open Source VNC client using HTML5 (WebSockets, Canvas).
  noVNC is both a VNC client JavaScript library as well as an application built on top of that library. noVNC runs well in any modern browser including mobile browsers (iOS and Android).

grade: stable
confinement: strict

parts:
    websockify:
        source: https://github.com/novnc/websockify/archive/v0.9.0.tar.gz
        plugin: dump
        organize:
            websockify/: utils/websockify/websockify/
            run: utils/websockify/
        # Avoid file name conflicts by not staging files from websockify that have the same names as those in novnc (docs/unimportant files only)
        stage:
            - -README.md
            - -docs/notes
    novnc:
        source: https://github.com/novnc/noVNC.git #https://github.com/novnc/noVNC/archive/v$SNAPCRAFT_PROJECT_VERSION.tar.gz 
        source-commit: e1d50c8c10563edcacebcaeb32d022906aa003d2
        plugin: dump
        stage-packages:
            - bash
            - jq
            - python-numpy
            - python3-numpy

hooks:
    configure:
        plugs: [network, network-bind]

apps:
    novnc:
        command: utils/launch.sh
        plugs: [network, network-bind]
    novncsvc:
        command: utils/svc_wrapper.sh
        daemon: forking
        plugs: [network, network-bind]
